repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        exclude: .*/tests/.*
  #      - id: trailing-whitespace
  #        exclude: (.*/tests/.*)|(*.md)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [ '--baseline', '.secrets.baseline.json' ]
        exclude: .*/tests/.*
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      # Run the linter
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format
        types_or: [ python, pyi ]
