[tox]
envlist =
    test-py{311}
    coverage-py{311}
    lint-py{311}
    badge-py{311}
skip_missing_interpreters = True
skipsdist = True
isolated_build = True

[base]
setenv = PYTHONPATH = $PYTHONPATH:projectname

[testenv:test-py{311}]
labels = test
allowlist_externals = poetry
commands_pre =
    poetry install --all-extras --with dev --no-root --sync
commands =
    poetry run pytest -v tests/unit tests/functional --show-capture=no --disable-pytest-warnings --junitxml=reports/unit-tests.xml
setenv = {[base]setenv}

[testenv:coverage-py{311}]
labels = coverage
allowlist_externals = poetry
commands_pre =
    poetry install --all-extras --with dev --no-root --sync
commands =
    poetry run pytest --cov projectname tests/unit tests/functional --cov-config=.coveragerc --cov-report term-missing --cov-fail-under=80 --cov-report xml:reports/coverage.xml
setenv = {[base]setenv}


[testenv:lint-py{311}]
labels = lint
allowlist_externals = poetry
commands_pre =
    poetry install --all-extras --with dev --no-root --sync
    python -c 'import sys; sys.path.append(".")'
commands =
    poetry run python -m pylint projectname --fail-under 9.0 --output-format=text:reports/linting.txt,text
setenv = {[base]setenv}

[testenv:badge-py{311}]
labels = badge
allowlist_externals = poetry
commands_pre =
    poetry install --all-extras --with dev --no-root --sync
commands =
    python tests/report.py
setenv = {[base]setenv}
